Fatal error checking 2

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -58,11 +58,11 @@ pipeline {
     
                     cd "$WORKSPACE" || exit 1
     
-                    # Check if .git exists
-                     if [ ! -d ".git" ]; then
-                    echo "Error: .git directory not found. Make sure this is a cloned Git repository."
-                    exit 1
-                     fi
+                     # Check if .git exists
+                     if [ ! -d ".git" ]; then
+                     echo "Error: .git directory not found. Make sure this is a cloned Git repository."
+                     exit 1
+                     fi
 
     
                     # Configure Git
